// reactTest/src/FormValidator.tsx
import React, { createContext, useContext, useState, useCallback } from 'react';
import { validateField, validateForm } from '../../shared/validation-rules';
import { UseFormValidatorReturn, FormValidatorProps, FormErrors } from '../../shared/types';

interface FormContextValue<T extends Record<string, any>> extends UseFormValidatorReturn<T> {
  // Additional context values can be added here
}

const FormContext = createContext<FormContextValue<any> | undefined>(undefined);

export const useFormValidator = <T extends Record<string, any>>(): UseFormValidatorReturn<T> => {
  const context = useContext(FormContext);
  if (!context) {
    throw new Error('useFormValidator must be used within a FormValidator component');
  }
  return context;
};

export const FormValidator = <T extends Record<string, any>>({ 
  fields, 
  initialValues = {} as T, 
  onSubmit, 
  children 
}: FormValidatorProps<T> & { children?: React.ReactNode }) => {
  const [values, setValues] = useState<T>(initialValues);
  const [errors, setErrors] = useState<FormErrors<T>>({});
  const [touched, setTouched] = useState<Partial<Record<keyof T, boolean>>>({});

  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const target = e.target;
    const { name, value, type } = target;
    let checkedValue: any = value;
    if (target instanceof HTMLInputElement && type === 'checkbox') {
      checkedValue = target.checked;
    }
    setValues(prev => ({
      ...prev,
      [name]: checkedValue
    }));

    // Clear error when field is modified
    if (errors[name as keyof T]) {
      setErrors(prev => ({
        ...prev,
        [name]: undefined
      }));
    }
  }, [errors]);

  const handleBlur = useCallback((e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setTouched(prev => ({
      ...prev,
      [name]: true
    }));

    // Validate field on blur
    const error = validateField(value, fields[name as keyof T], values);
    if (error) {
      setErrors(prev => ({
        ...prev,
        [name]: error
      }));
    }
  }, [fields, values]);

  const setFieldValue = useCallback((field: keyof T, value: any) => {
    setValues(prev => ({
      ...prev,
      [field]: value
    }));

    // Clear error when field is modified
    if (errors[field]) {
      setErrors(prev => ({
        ...prev,
        [field]: undefined
      }));
    }
  }, [errors]);

  const setFieldError = useCallback((field: keyof T, error: string | undefined) => {
    setErrors(prev => ({
      ...prev,
      [field]: error
    }));
  }, []);

  const validateFieldCallback = useCallback((field: keyof T, value: any) => {
    return validateField(value, fields[field], values);
  }, [fields, values]);

  const validateFormCallback = useCallback(() => {
    const formErrors = validateForm(values, fields);
    setErrors(formErrors as Partial<Record<keyof T, string>>);
    return Object.keys(formErrors).length === 0;
  }, [values, fields]);

  const handleSubmit = useCallback((e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    
    // Mark all fields as touched
    const allTouched: Partial<Record<keyof T, boolean>> = {};
    Object.keys(fields).forEach(field => {
      allTouched[field as keyof T] = true;
    });
    setTouched(allTouched);
    
    // Validate the form
    const isValid = validateFormCallback();
    if (isValid) {
      onSubmit(values);
    }
  }, [fields, onSubmit, validateFormCallback, values]);

  const contextValue: FormContextValue<T> = {
    values,
    errors,
    touched,
    handleChange: handleChange as any,
    handleBlur: handleBlur as any,
    handleSubmit: handleSubmit as any,
    setFieldValue,
    setFieldError,
    validateField: validateFieldCallback,
    validateForm: validateFormCallback
  };

  return (
    <FormContext.Provider value={contextValue}>
      <form onSubmit={handleSubmit}>
        {children}
      </form>
    </FormContext.Provider>
  );
};

// Form Field Component
export const FormField = <T extends Record<string, any>>({ 
  name, 
  label, 
  type = 'text', 
  placeholder, 
  children 
}: {
  name: keyof T;
  label: string;
  type?: string;
  placeholder?: string;
  children?: React.ReactNode;
}) => {
  const { values, errors, touched, handleChange, handleBlur } = useFormValidator<T>();
  const hasError = touched[name] && errors[name];

  return (
    <div style={{ marginBottom: '1rem' }}>
      <label htmlFor={name as string} style={{ display: 'block', marginBottom: '0.5rem' }}>
        {label}
      </label>
      {children ? (
        children
      ) : (
        <input
          type={type}
          id={name as string}
          name={name as string}
          value={values[name] as string}
          onChange={handleChange}
          onBlur={handleBlur}
          placeholder={placeholder}
          style={{
            width: '100%',
            padding: '0.5rem',
            border: hasError ? '1px solid red' : '1px solid #ccc',
            borderRadius: '4px'
          }}
        />
      )}
      {hasError && (
        <span style={{ color: 'red', fontSize: '0.8rem', marginTop: '0.25rem', display: 'block' }}>
          {errors[name]}
        </span>
      )}
    </div>
  );
};

// Submit Button Component
export const SubmitButton = ({ children = 'Submit' }: { children?: React.ReactNode }) => {
  return (
    <button
      type="submit"
      style={{
        padding: '0.5rem 1rem',
        backgroundColor: '#4CAF50',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer'
      }}
    >
      {children}
    </button>
  );
};

// vue3test/src/components/FormValidator.vue
<template>
  <form @submit.prevent="handleSubmit">
    <slot />
  </form>
</template>

<script lang="ts">
import { defineComponent, reactive, provide, inject } from 'vue';
import type { PropType } from 'vue';
import { validateForm, validateField } from '../../../shared/validation-rules';
import type { FormFields, FormErrors } from '../../../shared/types';

type FormContextValue = {
  values: Record<string, any>;
  errors: FormErrors<any>;
  touched: Partial<Record<string, boolean>>;
  handleChange: (e: Event) => void;
  handleBlur: (e: Event) => void;
  setFieldValue: (field: string | number | symbol, value: any) => void;
  setFieldError: (field: string | number | symbol, error: string | undefined) => void;
  validateField: (field: string | number | symbol, value: any) => string | undefined;
  validateForm: () => boolean;
};

const FormContextSymbol = Symbol('FormContext');

export function useFormValidator(): FormContextValue {
  const context = inject<FormContextValue>(FormContextSymbol);
  if (!context) {
    throw new Error('useFormValidator must be used within a FormValidator component');
  }
  return context;
}

export default defineComponent<{
  fields: FormFields<any>;
  initialValues?: Record<string, any>;
  onSubmit: (values: any) => void;
}>({
  name: 'FormValidator',
  props: {
    fields: {
      type: Object as PropType<FormFields<any>>,
      required: true
    },
    initialValues: {
      type: Object as PropType<Record<string, any>>,
      default: () => ({})
    },
    onSubmit: {
      type: Function as PropType<(values: any) => void>,
      required: true
    }
  },
  setup(props) {
    const values = reactive<Record<string, any>>({ ...props.initialValues });
    const errors = reactive<FormErrors<any>>({});
    const touched = reactive<Partial<Record<string, boolean>>>({});

    const handleChange = (e: Event) => {
      const target = e.target as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;
      const { name, value, type } = target;
      
      values[name] = type === 'checkbox' ? (target as HTMLInputElement).checked : value;
      
      // Clear error when field is modified
      if (errors[name]) {
        errors[name] = undefined;
      }
    };

    const handleBlur = (e: Event) => {
      const target = e.target as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;
      const { name, value } = target;
      
      touched[name] = true;
      
      // Validate field on blur
      const error = validateField(value, props.fields[name] || [], values);
      if (error) {
        errors[name] = error;
      }
    };

    const setFieldValue = (field: string | number | symbol, value: any) => {
      values[field as string] = value;
      
      // Clear error when field is modified
      if (errors[field as string]) {
        errors[field as string] = undefined;
      }
    };

    const setFieldError = (field: string | number | symbol, error: string | undefined) => {
      errors[field as string] = error;
    };

    const validateFieldCallback = (field: string | number | symbol, value: any) => {
      return validateField(value, props.fields[field as string] || [], values);
    };

    const validateFormCallback = () => {
      const formErrors = validateForm(values, props.fields);
      
      // Clear existing errors
      for (const field in errors) {
        if (Object.prototype.hasOwnProperty.call(errors, field)) {
          delete errors[field];
        }
      }
      
      // Set new errors
      for (const field in formErrors) {
        if (Object.prototype.hasOwnProperty.call(formErrors, field)) {
          errors[field] = formErrors[field];
        }
      }
      
      return Object.keys(formErrors).length === 0;
    };

    const handleSubmit = () => {
      // Mark all fields as touched
      for (const field in props.fields) {
        if (Object.prototype.hasOwnProperty.call(props.fields, field)) {
          touched[field] = true;
        }
      }
      
      // Validate the form
      const isValid = validateFormCallback();
      if (isValid) {
        props.onSubmit({ ...values });
      }
    };

    const contextValue: FormContextValue = {
      values,
      errors,
      touched,
      handleChange,
      handleBlur,
      setFieldValue,
      setFieldError,
      validateField: validateFieldCallback,
      validateForm: validateFormCallback
    };

    provide(FormContextSymbol, contextValue);

    return {
      handleSubmit
    };
  }
});
</script>
